x-airflow-common: &airflow-common
  build:
    context: ../
    dockerfile: infrastructure/docker/airflow/Dockerfile
    args:
      AIRFLOW_IMAGE_TAG: ${AIRFLOW_IMAGE_TAG:-3.1.6-python3.11}
      SPARK_TAG: ${SPARK_TAG:-4.1.1}
  user: "${AIRFLOW_UID:-50000}:0"
  env_file:
    - ../.env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_POSTGRES_USER}:${AIRFLOW_POSTGRES_PASSWORD}@postgres/${AIRFLOW_POSTGRES_DB}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    # Remote Logging
    - AIRFLOW__LOGGING__REMOTE_LOGGING=True
    - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=s3://${MINIO_BUCKET_LOGS:-dl-logs-3e91b5}/airflow
    - AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=aws_default
    # AWS Connection for MinIO (Secrets)
    - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
    - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
    - AWS_REGION_NAME=us-east-1
    - AWS_ENDPOINT_URL=http://minio:9000
    - _AIRFLOW_WWW_USER_USERNAME=${_AIRFLOW_WWW_USER_USERNAME:-admin}
    # ClickHouse Connection
    - CLICKHOUSE_HOST=clickhouse
    - CLICKHOUSE_PORT=8123
    - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
    - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
  volumes:
    - ../../orchestration/dags:/opt/airflow/dags
    - ../../logs:/opt/airflow/logs
    - ../../orchestration/plugins:/opt/airflow/plugins
    - ../../data:/opt/airflow/data
    - ../../processing:/opt/airflow/processing
    - ../../warehouse:/opt/airflow/warehouse
  networks:
    - data-network
  depends_on:
    postgres:
      condition: service_healthy

services:
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    deploy:
      resources:
        limits:
          cpus: '${AIRFLOW_WEBSERVER_CPU:-1.0}'
          memory: ${AIRFLOW_WEBSERVER_MEM:-2G}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always
    deploy:
      resources:
        limits:
          cpus: '${AIRFLOW_TRIGGERER_CPU:-0.5}'
          memory: ${AIRFLOW_TRIGGERER_MEM:-1G}
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      # Username handled in common env
      _AIRFLOW_WWW_USER_PASSWORD: '${AIRFLOW_ADMIN_PASSWORD}'
      _AIRFLOW_WWW_USER_ROLE: 'Admin'
      _AIRFLOW_WWW_USER_EMAIL: 'admin@example.com'
