services:
  metabase:
    image: metabase/metabase:${METABASE_TAG:-v0.58.3}
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_POSTGRES_DB:-metabase}
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_POSTGRES_USER:-metabase}
      MB_DB_PASS: ${METABASE_POSTGRES_PASSWORD:-metabase_password}
      MB_DB_HOST: postgres
    networks:
      - data-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - metabase_data:/metabase-data
    restart: always

volumes:
  metabase_data:
