services:
  postgres:
    image: postgres:${POSTGRES_TAG:-18}
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: postgres
      # Env vars for init script
      AIRFLOW_POSTGRES_USER: ${AIRFLOW_POSTGRES_USER}
      AIRFLOW_POSTGRES_PASSWORD: ${AIRFLOW_POSTGRES_PASSWORD}
      AIRFLOW_POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
      MLFLOW_POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      MLFLOW_POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      MLFLOW_POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
      METABASE_POSTGRES_USER: ${METABASE_POSTGRES_USER}
      METABASE_POSTGRES_PASSWORD: ${METABASE_POSTGRES_PASSWORD}
      METABASE_POSTGRES_DB: ${METABASE_POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ../scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_ROOT_USER}"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - data-network

  minio:
    image: quay.io/minio/aistor/minio:${MINIO_TAG:-latest}
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /mnt/data --console-address ":9001" --license /minio.license
    volumes:
      - minio-data:/mnt/data
      - ../secrets/minio.license:/minio.license
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - data-network

  minio-init:
    image: minio/mc:${MINIO_TAG:-RELEASE.2025-09-07T16-13-09Z}
    networks:
      - data-network
    depends_on:
      - minio
    volumes:
        - ../scripts/init-minio.sh:/scripts/init-minio.sh
    env_file:
      - ../.env
    entrypoint: /scripts/init-minio.sh

  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_TAG:-25.8.15-alpine}
    deploy:
      resources:
        limits:
          memory: ${CLICKHOUSE_MEM_LIMIT:-4G}
    ports:
      - "8123:8123"
      - "9005:9000"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-paysim}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - data-network


