name: 'dbt_clickhouse'
version: '1.0.0'
config-version: 2

profile: 'lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_clickhouse:
    materialized: view
    
    staging:
      materialized: view
      schema: staging
      
    intermediate:
      materialized: view
      schema: intermediate
      
    marts:
      materialized: table
      schema: marts
      clickhouse_engine: MergeTree()
      clickhouse_partition_by: toYYYYMMDD(transaction_time)
