name: 'paysim_warehouse'
version: '1.0.0'
config-version: 2

profile: 'lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  paysim_warehouse:
    materialized: view
    
    staging:
      materialized: view
      schema: staging
      
    core:
      materialized: table
      schema: core
      
    marts:
      materialized: table
      schema: marts
