lakehouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: finance_dw
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'clickhouse_admin') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse_password') }}"
      secure: false
      verify: false
      connect_timeout: 30 
